<a href="https://colab.research.google.com/github/VaishnaviBairagoni/Probability-and-Statistics/blob/main/LAB-01_(Python%20Basics).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
a=[1,2,34,6,32,14,65,7]#create An Array
arr=np.array(a)
print(arr)

[ 1  2 34  6 32 14 65  7]


In [3]:
arr=np.array([1,2,34,6,32,14,65,7])
print(arr)
print(arr[0])
print(arr[2])
aa=[[1,2,3,4],[4,2,3,6]]#Create a 2D array
A=np.array(aa)
print(A)

[ 1  2 34  6 32 14 65  7]
1
34
[[1 2 3 4]
 [4 2 3 6]]


In [5]:
A=np.array([[1,2,3,4],[4,2,3,6]])
print(A)
print(type(A))
print(type(arr))
np.ndim(arr)#dimensions of array
np.ndim(A)
print(np.size(arr))
print(np.size(A))
print(np.shape(arr))
print(np.shape(A))

[[1 2 3 4]
 [4 2 3 6]]
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
8
8
(8,)
(2, 4)


In [6]:
#ROWS AND COLUMNS OF AN ARRAY
A=np.array([[1,2,3],[3,4,5],[4,5,6]])
print(A)
#PRINT ROWS
print(A[0,:])
print(A[1,:])
print(A[2,:])

[[1 2 3]
 [3 4 5]
 [4 5 6]]
[1 2 3]
[3 4 5]
[4 5 6]


In [7]:
#PRINT COLUMNS
print(A[:,0])
print(A[:,1])
print(A[:,2])
#print an element in a matrix
print(A[2,1])


[1 3 4]
[2 4 5]
[3 5 6]
5
